os:
  - linux
  - osx

language: c

compiler:
  - gcc

addons:
  homebrew:
    packages:
    - sdl2
    - boost
    update: true
  apt:
    packages:
    - libsdl2-dev
    - libboost-all-dev


script:
  - cmake .
  - cmake --build .
