os:
  - linux
  - osx

language: c

compiler:
  - gcc

addons:
  homebrew:
    packages:
    - sdl2

addons:
  apt:
    packages:
    - libsdl2
    - libsdl2-dev


script:
  - cmake .
  - cmake --build build
